/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Proyecto.modelo.dt.PreguntasDT;
import Proyecto.modelo.facade.sistemaFacade;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luis
 */
public class AltaPreguntas extends javax.swing.JInternalFrame {
    sistemaFacade fac =new sistemaFacade();
    PreguntasDT dt = new PreguntasDT();


    /**
     * Creates new form AltaPreguntas
     */
    public AltaPreguntas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEnunciado = new javax.swing.JTextField();
        txtIdRespuestas = new javax.swing.JTextField();
        txtIdExamenes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Alta Preguntas");

        jLabel2.setText("enunciado");

        jLabel3.setText("idRespuestas");

        jLabel4.setText("idExamenes");

        txtEnunciado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEnunciadoKeyTyped(evt);
            }
        });

        txtIdRespuestas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdRespuestasKeyTyped(evt);
            }
        });

        txtIdExamenes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdExamenesKeyTyped(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(pantallaLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2))
                    .addGroup(pantallaLayout.createSequentialGroup()
                        .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(78, 78, 78)
                        .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtIdRespuestas, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(txtIdExamenes))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdRespuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtIdExamenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //codigo para validar o dar mensaje de campos vacios (ButtonGuardar-events-ActionPerformed) 

            if(txtEnunciado.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Falta campos por llenar!!!","error",JOptionPane. ERROR_MESSAGE);
          }
            else if(txtIdRespuestas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Falta campos por llenar!!!","error",JOptionPane. ERROR_MESSAGE);
          }
            else if(txtIdExamenes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Falta campos por llenar!!!","error",JOptionPane. ERROR_MESSAGE);
          }
           
             else{
        
         try {
            if(dt != null){
                
                
                dt.setEnunciado(txtEnunciado.getText());
                txtEnunciado.setText("");
                dt.setIdRespuestas(Integer.parseInt(txtIdRespuestas.getText()));
                txtIdRespuestas.setText("");
                dt.setIdExamenes(Integer.parseInt(txtIdExamenes.getText()));
                txtIdExamenes.setText("");
                fac.nuevoPreguntas(dt);
                
            }else{

            }
            JOptionPane.showMessageDialog(this, "Datos guardados");
        } catch (Exception e) {
            Logger.getLogger(AltaPreguntas.class.getName()).log(Level.SEVERE,null, e);
        }
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEnunciadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnunciadoKeyTyped
        // TODO add your handling code here:
        //codigo para validar los campos de letras(events-Key-KeyType)

 char c = evt.getKeyChar();
        
        if((c<'a'  || c>'z') && (c<'A'  )| c>'Z' )evt.consume();
    }//GEN-LAST:event_txtEnunciadoKeyTyped

    private void txtIdRespuestasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdRespuestasKeyTyped
        // TODO add your handling code here:
        //codigo para validar los campos de numeros(events-Key-KeyType)

    char c = evt.getKeyChar();
        
        if(c<'0'  || c>'9') evt.consume();
    }//GEN-LAST:event_txtIdRespuestasKeyTyped

    private void txtIdExamenesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdExamenesKeyTyped
        // TODO add your handling code here:
        //codigo para validar los campos de numeros(events-Key-KeyType)

    char c = evt.getKeyChar();
        
        if(c<'0'  || c>'9') evt.consume();
    }//GEN-LAST:event_txtIdExamenesKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pantalla;
    private javax.swing.JTextField txtEnunciado;
    private javax.swing.JTextField txtIdExamenes;
    private javax.swing.JTextField txtIdRespuestas;
    // End of variables declaration//GEN-END:variables
}
